management:
  endpoint:
    info:
      enabled: true
    health:
      show-details: when_authorized
  endpoints:
    web:
      exposure:
        include: "*"
      #base-path: "/monitoring"

logging:
  level:
    au.com.marlo: DEBUG

spring:
  h2:
    console:
      enabled: true
  datasource:
    name: springit
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
info:
  app:
    name: "Spring Reddit"
    description: "Spring Boot reddit clone"
    version: "1.0.0"